### ISSUE TITLE
Kibana Plugin Installation

### ISSUE THREAD

**Issue by archcorsair** [mercuriete/docker-logstash-fluentd-elastic-kibana#1]
Kibana Dockerfile contains the command:
`RUN kibana plugin --install elastic/sense`

I updated the script to (new way):
`RUN kibana-plugin install elastic/sense`

and get:
```
Attempting to transfer from elastic/sense
Attempting to transfer from https://artifacts.elastic.co/downloads/kibana-plugins/elastic/sense/elastic/sense-5.2.0.zip
Plugin installation was unsuccessful due to error "No valid url specified."
```
It seems that sense is now a legacy product. Is there an alternative way to get all these services running successfully in one container?

**Comment by mercuriete** [comment]
@archcorsair 
this failure is due kibana 5.0 probably.
i have to specify this was done in kibana 4.0.

Now in kibana 5.0 sense and timelion are part of kibana core.

I will try to fix it.

edit:  you can delete that line safely. I think it would work fine.

**Comment by mercuriete** [comment]
@archcorsair 

It should be solved with https://github.com/mercuriete/docker-logstash-fluentd-elastic-kibana/commit/b39958ee5d46a4f5eb1961c968a7e2c02ff7bfef

closing.

Now fluentd is not working with docker toolbox because of a problem with VOLUMES.

**Comment by mercuriete** [comment]
closing

**Comment by archcorsair** [comment]
Awesome! Thank you. Could you please email me? I have a few questions I'd like to ask without polluting this issue's thread. archcorsair@gmail.com

**Comment by mercuriete** [comment]
Hi! @archcorsair 
for me is better that you open a new issue with a question.
Because maybe some other people could have the same question.

:smile:
